version: '2'
services:
  postgres:
    build: .
    links:
      - "db:database"
    db:
      image: postgres
    ports:
     - "5432:5432"
    volumes:
     - ./postgres-volume:/home
    environment:
     - DEBUG=false

     - DB_USER=
     - DB_PASS=
     - DB_NAME=
     - DB_TEMPLATE=

     - DB_EXTENSION=

     - REPLICATION_MODE=
     - REPLICATION_USER=
     - REPLICATION_PASS=
     - REPLICATION_SSLMODE=
  
 
  rstudio:
    build: rstudio
    image: rstudio
    volumes:
     - ./rstudio-volume:/home
    environment:
     - env variables
